global:

  weixin_token: 5b6fc4d19b7511e2bdb0c8bcc88efaac
  weixin_callback: http://weixin.dev.longmaworks.com/cb/weixin

production:
  mysql:
    username: tank
    password: tank_pwd
    
    host_master: localhost
    port_master: 3306

    host_slave: localhost
    port_slave: 3306

    database: tank

    echo: false

testing:

development:

  mysql:
    username: tank
    password: tank
    
    host_master: localhost
    port_master: 3306

    host_slave: localhost
    port_slave: 3306

    database: tank

    echo: false
